services:
  bookify_api:
    image: javohirkhursanboyev/bookify_api:latest
    build:
      context: .
      dockerfile: src\Bookify.Api\Dockerfile
    container_name: bookify_api
    restart: always
    ports:
      - "8081:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Prod
      - ASPNETCORE_URLS=http://+:8080
    depends_on:
      - bookify_db
    networks:
      - bookify_network

  bookify_db:
    image: postgres:latest  
    container_name: bookify_db
    restart: always
    environment:
      POSTGRES_USER: bookify_user
      POSTGRES_PASSWORD: root
      POSTGRES_DB: bookifyDb
    ports:
      - "5432:5432"
    volumes:
      - bookify_db_data:/var/lib/postgresql
    networks:
      - bookify_network  

  bookify_idp:
    container_name: bookify_idp
    image: quay.io/keycloak/keycloak:latest
    restart: always
    command: start-dev --import-realm
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    volumes:
      - bookify_idp_data:/opt/keycloak/data
      - ./.files/bookify-realm-export.json:/opt/keycloak/data/import/realm.json
    ports:
      - 18080:8080
volumes:
    bookify_db_data:
    bookify_idp_data:

networks:
    bookify_network:
        driver: bridge